name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t aiecommerce-backend:latest .


      - name: Deploy backend
        run: |
          docker compose \
            --env-file /home/hanu/server/projects/AiEcommerceBackend/.env \
            -f "$GITHUB_WORKSPACE/docker-compose.yml" \
            up -d --force-recreate backend

      - name: Check deployment
        run: |
          docker compose \
            --env-file /home/hanu/server/projects/AiEcommerceBackend/.env \
            -f "$GITHUB_WORKSPACE/docker-compose.yml" \
            ps backend
          docker logs --tail 80 aiecommerce-backend
      
